#!/usr/bin/env python3
"""Converts the per-language Localizable.strings into a single String Catalog
(Localizable.xcstrings), for teams who prefer Xcode's catalog editor.

Usage:  python3 tools/make_xcstrings.py
Output: SpaceMonger/Localizable.xcstrings

NOTE: do not ship both .strings and .xcstrings for the same table — pick one.
This is provided so you can migrate when you want; the app currently uses the
.strings + .stringsdict files generated by make_locales.py.
"""
import glob
import json
import os
import re

BASE = os.path.join(os.path.dirname(__file__), "..", "SpaceMonger")
SOURCE_LANG = "en"

_PAIR = re.compile(r'"((?:[^"\\]|\\.)*)"\s*=\s*"((?:[^"\\]|\\.)*)"\s*;')


def unescape(s):
    return s.encode("utf-8").decode("unicode_escape") if "\\" in s else s


def parse_strings(path):
    out = {}
    with open(path, encoding="utf-8") as f:
        for m in _PAIR.finditer(f.read()):
            out[unescape(m.group(1))] = unescape(m.group(2))
    return out


def main():
    langs = {}
    for lproj in sorted(glob.glob(os.path.join(BASE, "*.lproj"))):
        code = os.path.basename(lproj)[:-len(".lproj")]
        sfile = os.path.join(lproj, "Localizable.strings")
        if os.path.exists(sfile):
            langs[code] = parse_strings(sfile)

    keys = set()
    for table in langs.values():
        keys.update(table.keys())

    catalog = {"sourceLanguage": SOURCE_LANG, "version": "1.0", "strings": {}}
    for key in sorted(keys):
        localizations = {}
        for code, table in langs.items():
            if key in table:
                localizations[code] = {
                    "stringUnit": {"state": "translated", "value": table[key]}
                }
        catalog["strings"][key] = {"localizations": localizations}

    out = os.path.join(BASE, "Localizable.xcstrings")
    with open(out, "w", encoding="utf-8") as f:
        json.dump(catalog, f, ensure_ascii=False, indent=2)
    print(f"Wrote {out} with {len(keys)} keys across {len(langs)} languages.")


if __name__ == "__main__":
    main()
